<?php
declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class ConstituencyDataSeeder extends AbstractSeed
{
    public function run(): void
    {
        // Disable foreign key checks to allow insertion of hierarchical data without ordering issues
        $this->execute("SET FOREIGN_KEY_CHECKS = 0");

        // 1. Ensure Categories 1-10 exist
        $categories = [
            ['id' => 1, 'name' => 'Water', 'slug' => 'water'],
            ['id' => 2, 'name' => 'Power', 'slug' => 'power'],
            ['id' => 3, 'name' => 'Roads', 'slug' => 'roads'],
            ['id' => 4, 'name' => 'Sanitation', 'slug' => 'sanitation'],
            ['id' => 5, 'name' => 'Health', 'slug' => 'health'],
            ['id' => 6, 'name' => 'Education', 'slug' => 'education'],
            ['id' => 7, 'name' => 'Agriculture', 'slug' => 'agriculture'],
            ['id' => 8, 'name' => 'Employment', 'slug' => 'employment'],
            ['id' => 9, 'name' => 'Social Protection', 'slug' => 'social-protection'],
            ['id' => 10, 'name' => 'Security & Governance', 'slug' => 'security-governance'],
        ];

        foreach ($categories as $cat) {
            $this->execute("INSERT IGNORE INTO categories (id, name, slug, created_at, updated_at) VALUES ({$cat['id']}, '{$cat['name']}', '{$cat['slug']}', NOW(), NOW())");
        }

        // 2. Seed Locations
        $locations = [
            [1, 'BEDII', 'community', NULL, 'active'],
            [2, 'ABOANIDUA', 'community', NULL, 'active'],
            [3, 'NTRENTRESO', 'community', NULL, 'active'],
            [4, 'AKOTI', 'community', NULL, 'active'],
            [5, 'PABOASE', 'community', NULL, 'active'],
            [6, 'APPIAHKROM', 'community', NULL, 'active'],
            [7, 'AHWIAA', 'community', NULL, 'active'],
            [8, 'FUTA', 'community', NULL, 'active'],
            [9, 'PENAKROM', 'community', NULL, 'active'],
            [10, 'NYAMEBEKYERE', 'community', NULL, 'active'],
            [11, 'BOSOMOISO', 'community', NULL, 'active'],
            [12, 'AFEREE', 'community', NULL, 'active'],
            [13, 'ABODUAM', 'community', NULL, 'active'],
            [14, 'EWIASE-NGAKAIN', 'community', NULL, 'active'],
            [15, 'AMAFIE', 'community', NULL, 'active'],
            [16, 'ABOBOYAA', 'community', NULL, 'active'],
            [17, 'WIAWSO', 'community', NULL, 'active'],
            [18, 'KESSEKROM', 'community', NULL, 'active'],
            [19, 'AHWIAM', 'community', NULL, 'active'],
            [20, 'MPOMAM', 'community', NULL, 'active'],
            [21, 'DWENASE', 'community', NULL, 'active'],
            [22, 'NSUONSUA', 'community', NULL, 'active'],
            [23, 'TANOSO', 'community', NULL, 'active'],
            [24, 'DATANO', 'community', NULL, 'active'],
            [25, 'AHOKWAA', 'community', NULL, 'active'],
            [26, 'DOMEABRA', 'community', NULL, 'active'],
            [27, 'KETEBOI', 'community', NULL, 'active'],
            [28, 'PUNIKROM', 'community', NULL, 'active'],
            [29, 'CAMP', 'community', NULL, 'active'],
            [30, 'ANYINABIRIM', 'community', NULL, 'active'],
            [31, 'ABRABRA', 'community', NULL, 'active'],
            [32, 'NKONYA', 'community', NULL, 'active'],
            [33, 'ATTORKROM', 'community', NULL, 'active'],
            [34, 'SUI', 'community', NULL, 'active'],
            [35, 'BOAKO', 'community', NULL, 'active'],
            [36, 'AKURAFU', 'community', NULL, 'active'],
            [37, 'GYAMPOKROM', 'community', NULL, 'active'],
            [38, 'AMPABAME', 'community', NULL, 'active'],
            [39, 'ABOAGYEKROM', 'community', NULL, 'active'],
            [41, 'KUNUMA', 'community', NULL, 'active'],
            [42, 'AFRIMKROM', 'community', NULL, 'active'],
            [43, 'AKYEAKYEN', 'community', NULL, 'active'],
            [44, 'KANKYEABO', 'community', NULL, 'active'],
            [46, 'ASAFO', 'community', NULL, 'active'],
            [47, 'ASAWINSO', 'community', NULL, 'active'],
            [48, 'KOJINA', 'community', NULL, 'active'],
            [49, 'ESSAKROM', 'community', NULL, 'active'],
            [50, 'AGONA SAFO', 'suburb', 1, 'active'],
            [51, 'OLD BEDII', 'suburb', 1, 'active'],
            [52, 'LARWEHKROM', 'community', 5, 'active'],
            [53, 'PROJECT', 'suburb', 52, 'active'],
            [54, 'KWAME ANINIKROM', 'suburb', 52, 'active'],
            [55, 'KYEREBOSO', 'suburb', 7, 'active'],
            [56, 'ALOMUM', 'community', 10, 'active'],
            [57, 'DWENEWOHO', 'community', 12, 'active'],
            [58, 'BETEKYE', 'suburb', 13, 'active'],
            [59, 'GARDEN', 'suburb', 17, 'active'],
            [60, 'OLD ADIEMBRA', 'suburb', 17, 'active'],
            [61, 'NEW ADIEMBRA', 'suburb', 17, 'active'],
            [62, 'SUSUMINITE3', 'suburb', 17, 'active'],
            [63, 'NEWTOWN', 'suburb', 17, 'active'],
            [64, 'SOMAAKROM', 'suburb', 17, 'active'],
            [65, 'ABUOTEM', 'suburb', 17, 'active'],
            [66, 'KWASIPATABO', 'suburb', 17, 'active'],
            [67, 'ASAMAN', 'suburb', 17, 'active'],
            [68, 'SOUTH AFRICA', 'suburb', 17, 'active'],
            [69, 'AKAALOMBO', 'suburb', 17, 'active'],
            [70, 'ASIKAFUO AMMANTEM', 'suburb', 17, 'active'],
            [71, 'MEMPE-ASEM', 'suburb', 17, 'active'],
            [72, 'ZONGO', 'suburb', 17, 'active'],
            [73, 'LOWCOST', 'suburb', 17, 'active'],
            [74, 'KWAADUKROM', 'suburb', 19, 'active'],
            [75, 'NO.2 (BOAMAKROM)', 'suburb', 19, 'active'],
            [76, 'GYATOKROM', 'community', 19, 'active'],
            [77, 'ATEKYEM', 'suburb', 21, 'active'],
            [78, 'AKURASE', 'suburb', 21, 'active'],
            [79, 'EIGHTEEN', 'suburb', 21, 'active'],
            [80, 'ZONGO', 'suburb', 21, 'active'],
            [81, 'NEW SITE', 'suburb', 21, 'active'],
            [82, 'COMPOUND', 'suburb', 21, 'active'],
            [83, 'KOKOKRO', 'suburb', 21, 'active'],
            [84, 'NSUEKRO', 'suburb', 21, 'active'],
            [85, 'KUZENSO', 'suburb', 21, 'active'],
            [86, 'ANGLO', 'community', 22, 'active'],
            [87, 'BAAKONGA', 'community', 22, 'active'],
            [88, 'ENSONYAMEYE', 'community', 22, 'active'],
            [89, 'KWAMEBUO', 'community', 22, 'active'],
            [90, 'KROBOM', 'community', 22, 'active'],
            [91, 'AYILEKRO', 'community', 22, 'active'],
            [92, 'KWASI ARMAKROM', 'suburb', 89, 'active'],
            [93, 'ADAMU', 'suburb', 91, 'active'],
            [94, 'ABOPROE', 'suburb', 91, 'active'],
            [95, 'AHODWO', 'suburb', 23, 'active'],
            [96, 'DIVISION', 'suburb', 23, 'active'],
            [97, 'EFO JUNCTION', 'suburb', 23, 'active'],
            [98, 'FUAKYEKROM', 'community', 23, 'active'],
            [99, 'NYAMEGYESO', 'community', 23, 'active'],
            [100, 'ESONEBIAGYA', 'suburb', 98, 'active'],
            [101, 'MEMPE-ASEM', 'suburb', 98, 'active'],
            [102, 'KWADWO ANTO', 'suburb', 98, 'active'],
            [103, 'KUSASI-LINE', 'suburb', 24, 'active'],
            [104, 'SUHENSO', 'community', 25, 'active'],
            [105, 'OWUO ABOROSO', 'suburb', 26, 'active'],
            [106, 'BOWOBRA', 'community', 26, 'active'],
            [107, 'KYEAMEKRO', 'community', 26, 'active'],
            [108, 'APENTEMADI', 'community', 26, 'active'],
            [109, 'NYAME NNAE', 'community', 26, 'active'],
            [110, 'SWANZY', 'community', 26, 'active'],
            [111, 'PIASE', 'community', 26, 'active'],
            [112, 'OBIA NTOBI', 'suburb', 109, 'active'],
            [113, 'OSEI MPAMBRO', 'suburb', 109, 'active'],
            [114, 'KRAMO TENTEN', 'suburb', 109, 'active'],
            [115, 'NYAME NNAI ZONGO', 'suburb', 109, 'active'],
            [116, 'MORGAN', 'suburb', 110, 'active'],
            [117, 'ADIYAAKRO', 'suburb', 110, 'active'],
            [118, 'SHED', 'suburb', 110, 'active'],
            [119, 'AMADU KROM', 'suburb', 110, 'active'],
            [120, 'TUPA', 'suburb', 110, 'active'],
            [121, 'MATAPOLI', 'suburb', 111, 'active'],
            [122, 'EMIESO', 'suburb', 27, 'active'],
            [123, 'GYAASEHENE', 'suburb', 27, 'active'],
            [124, 'KAINA-C', 'suburb', 27, 'active'],
            [125, 'GARIBAKRO', 'suburb', 27, 'active'],
            [126, 'ADOWA NKWANTA', 'suburb', 28, 'active'],
            [127, 'ADUHENEKROM', 'suburb', 28, 'active'],
            [128, 'ADENKYIN', 'suburb', 28, 'active'],
            [129, 'KRAMOKRO', 'community', 28, 'active'],
            [130, 'AGYA AKUFO', 'suburb', 129, 'active'],
            [131, 'KOFIKROM', 'suburb', 29, 'active'],
            [132, 'BOMODEN', 'suburb', 29, 'active'],
            [133, 'BREDI', 'suburb', 29, 'active'],
            [134, 'ASANTEKROM', 'suburb', 29, 'active'],
            [135, 'POWERKROM', 'suburb', 29, 'active'],
            [136, 'AKUAPIM NKWANTA', 'suburb', 29, 'active'],
            [137, 'BANGROMESAA', 'suburb', 29, 'active'],
            [138, 'GYIDI', 'suburb', 30, 'active'],
            [139, 'KOFORIDUA', 'suburb', 30, 'active'],
            [140, 'MILE 2', 'community', 30, 'active'],
            [141, 'MILE-3', 'community', 30, 'active'],
            [142, 'MILE-4', 'community', 30, 'active'],
            [143, 'MILE-5', 'community', 30, 'active'],
            [144, 'MILE-3 FOREST', 'suburb', 141, 'active'],
            [145, 'GYAAKYE', 'suburb', 141, 'active'],
            [146, 'MILE-4 FOREST', 'suburb', 142, 'active'],
            [147, 'ASUOGYA', 'suburb', 143, 'active'],
            [148, 'KOO NSIA', 'suburb', 143, 'active'],
            [149, 'NYAME NNAE-ABRABRA', 'suburb', 31, 'active'],
            [150, 'ABRABRA FOREST', 'suburb', 31, 'active'],
            [151, 'KUMIKROM', 'suburb', 31, 'active'],
            [152, 'PEWODIE', 'community', 32, 'active'],
            [153, 'SUI NKWANTA', 'community', 32, 'active'],
            [154, 'ATTA CAMP', 'community', 32, 'active'],
            [155, 'PAPA KWAME', 'suburb', 152, 'active'],
            [156, 'MFUMKROM', 'suburb', 154, 'active'],
            [157, 'KROBO LINE', 'suburb', 154, 'active'],
            [158, 'BARRACKS', 'suburb', 35, 'active'],
            [159, 'BUADAC', 'suburb', 35, 'active'],
            [160, 'ASUOEBA', 'suburb', 158, 'active'],
            [161, 'KWANANE', 'community', 35, 'active'],
            [162, 'ABODUAM', 'suburb', 161, 'active'],
            [163, 'TEABANTE', 'suburb', 161, 'active'],
            [164, 'GRUMAHENE', 'suburb', 161, 'active'],
            [165, 'KWADWO HUNU', 'suburb', 36, 'active'],
            [166, 'SHED', 'suburb', 36, 'active'],
            [167, 'KUMORKRO', 'suburb', 36, 'active'],
            [168, 'AMPROMBI', 'suburb', 36, 'active'],
            [169, 'BOADUKROM', 'suburb', 36, 'active'],
            [170, 'YAWKWATIAKRO', 'suburb', 36, 'active'],
            [171, 'FAWOMAN', 'community', 36, 'active'],
            [172, 'NYETINA', 'community', 36, 'active'],
            [173, 'ABONSE', 'community', 37, 'active'],
            [174, 'BEKYIWA', 'community', 37, 'active'],
            [175, 'AWUTU', 'suburb', 173, 'active'],
            [176, 'POSTMASTER', 'suburb', 174, 'active'],
            [177, 'MANGOASE', 'suburb', 174, 'active'],
            [178, 'AMANO', 'suburb', 174, 'active'],
            [179, 'OYOKO', 'suburb', 174, 'active'],
            [180, 'ABOSO', 'suburb', 174, 'active'],
            [181, 'ABIGYAN LINE', 'suburb', 174, 'active'],
            [182, 'AFADIKROM', 'community', 38, 'active'],
            [183, 'LARBIKROM', 'community', 38, 'active'],
            [184, 'MADINA', 'community', 38, 'active'],
            [185, 'KWASI ADJEIKROM', 'suburb', 39, 'active'],
            [186, 'GYAMPO', 'suburb', 39, 'active'],
            [187, 'DAWOME', 'suburb', 39, 'active'],
            [188, 'OJOBI', 'suburb', 39, 'active'],
            [189, 'ASIEDUKRO', 'suburb', 39, 'active'],
            [190, 'AMANKWAKRO', 'suburb', 39, 'active'],
            [191, 'BREKULINE', 'community', 39, 'active'],
            [192, 'MENSAHLINE KWASIKRU', 'community', 39, 'active'],
            [193, 'KAE AWURADE', 'suburb', 192, 'active'],
            [194, 'TUTUCAMP', 'suburb', 192, 'active'],
            [195, 'NANA YARO', 'suburb', 41, 'active'],
            [196, 'NANA HARUNA', 'suburb', 41, 'active'],
            [197, 'SUI ANO', 'community', 41, 'active'],
            [198, 'BRE NYE KWA', 'suburb', 44, 'active'],
            [199, 'ADUANE KYEN SIKA', 'suburb', 44, 'active'],
            [200, 'ROME', 'community', 45, 'active'],
            [201, 'ANKAASE', 'suburb', 46, 'active'],
            [202, 'KWAME DRUG STORE', 'suburb', 46, 'active'],
            [203, 'ZUGU LINE', 'suburb', 47, 'active'],
            [204, 'GYATOKROM', 'suburb', 47, 'active'],
            [205, 'ACKAAKROM', 'suburb', 47, 'active'],
            [206, 'DE-BEAT', 'suburb', 47, 'active'],
            [207, 'SEFWI LINE', 'suburb', 47, 'active'],
            [208, 'BILI BOY', 'suburb', 47, 'active'],
            [209, 'OBAATAASO', 'suburb', 47, 'active'],
            [210, 'ZAB ZERO', 'suburb', 47, 'active'],
            [211, 'MARKET AREA', 'suburb', 47, 'active'],
            [212, 'MEMENEDA KOKOO', 'suburb', 47, 'active'],
            [213, 'WANOPE ASEM', 'suburb', 47, 'active'],
            [214, 'ATHURKROM', 'suburb', 48, 'active'],
            [215, 'AKWASI ADDAEKROM', 'community', 49, 'active'],
        ];

        foreach ($locations as $loc) {
            $this->execute(sprintf(
                "INSERT INTO locations (id, name, type, parent_id, status, created_at, updated_at) 
                 VALUES (%d, '%s', '%s', %s, '%s', NOW(), NOW()) 
                 ON DUPLICATE KEY UPDATE name='%s', type='%s', parent_id=%s, status='%s', updated_at=NOW()",
                $loc[0], addslashes($loc[1]), $loc[2], ($loc[3] === NULL ? 'NULL' : $loc[3]), $loc[4],
                addslashes($loc[1]), $loc[2], ($loc[3] === NULL ? 'NULL' : $loc[3]), $loc[4]
            ));
        }

        // 3. Seed Sectors
        $sectors = [
            [1, 1, 'Urban Water Supply', 'urban-water-supply', NULL, 'active'],
            [2, 1, 'Rural Water Supply', 'rural-water-supply', NULL, 'active'],
            [3, 1, 'Water Infrastructure & Flood Control', 'water-infrastructure-flood-control', NULL, 'active'],
            [4, 2, 'Power Supply', 'power-supply', NULL, 'active'],
            [5, 2, 'Electrical Infrastructure', 'electrical-infrastructure', NULL, 'active'],
            [6, 2, 'Street Lighting', 'street-lighting', NULL, 'active'],
            [7, 3, 'Feeder Roads', 'feeder-roads', NULL, 'active'],
            [8, 3, 'Urban Roads & Streets', 'urban-roads-streets', NULL, 'active'],
            [9, 3, 'Bridges & Transport Structures', 'bridges-transport-structures', NULL, 'active'],
            [10, 4, 'Waste Management', 'waste-management', NULL, 'active'],
            [11, 4, 'Drainage & Sewage', 'drainage-sewage', NULL, 'active'],
            [12, 4, 'Public Toilets & Hygiene', 'public-toilets-hygiene', NULL, 'active'],
            [13, 5, 'Health Facilities', 'health-facilities', NULL, 'active'],
            [14, 5, 'Health Personnel & Services', 'health-personnel-services', NULL, 'active'],
            [15, 5, 'Medical Supplies & Public Health', 'medical-supplies-public-health', NULL, 'active'],
            [16, 6, 'School Infrastructure', 'school-infrastructure', NULL, 'active'],
            [17, 6, 'Teaching & Learning', 'teaching-learning', NULL, 'active'],
            [18, 6, 'School Welfare & Access', 'school-welfare-access', NULL, 'active'],
            [19, 7, 'Crop Farming', 'crop-farming', NULL, 'active'],
            [20, 7, 'Livestock & Fisheries', 'livestock-fisheries', NULL, 'active'],
            [21, 7, 'Agricultural Infrastructure & Markets', 'agricultural-infrastructure-markets', NULL, 'active'],
            [22, 8, 'Unemployment', 'unemployment', NULL, 'active'],
            [23, 8, 'Skills & Training', 'skills-training', NULL, 'active'],
            [24, 8, 'Labour Issues', 'labour-issues', NULL, 'active'],
            [25, 9, 'Financial & Material Support', 'financial-material-support', NULL, 'active'],
            [26, 9, 'Vulnerable Groups Support', 'vulnerable-groups-support', NULL, 'active'],
            [27, 9, 'Social Protection Programs', 'social-protection-programs', NULL, 'active'],
            [28, 10, 'Security & Safety', 'security-safety', NULL, 'active'],
            [29, 10, 'Land & Housing', 'land-housing', NULL, 'active'],
            [30, 10, 'Governance & Civic Issues', 'governance-civic-issues', NULL, 'active'],
        ];

        foreach ($sectors as $sec) {
            $this->execute(sprintf(
                "INSERT INTO sectors (id, category_id, name, slug, description, status, created_at, updated_at) 
                 VALUES (%d, %d, '%s', '%s', %s, '%s', NOW(), NOW()) 
                 ON DUPLICATE KEY UPDATE category_id=%d, name='%s', slug='%s', description=%s, status='%s', updated_at=NOW()",
                $sec[0], $sec[1], addslashes($sec[2]), $sec[3], ($sec[4] === NULL ? 'NULL' : "'".addslashes($sec[4])."'"), $sec[5],
                $sec[1], addslashes($sec[2]), $sec[3], ($sec[4] === NULL ? 'NULL' : "'".addslashes($sec[4])."'"), $sec[5]
            ));
        }

        // 4. Seed Sub-Sectors (Large set)
        // I will seed the first batch to avoid overly large file issues in this tool call, but I'll make it comprehensive.
        $subSectors = [
            [1, 1, 'No water supply', NULL, 'active'],
            [2, 1, 'Irregular water flow', NULL, 'active'],
            [3, 1, 'Low water pressure', NULL, 'active'],
            [4, 1, 'Burst water pipes', NULL, 'active'],
            [5, 1, 'Broken water meters', NULL, 'active'],
            [6, 1, 'Illegal water connections', NULL, 'active'],
            [7, 1, 'Billing disputes', NULL, 'active'],
            [8, 1, 'Poor water quality', NULL, 'active'],
            [9, 1, 'Old/damaged pipelines', NULL, 'active'],
            [10, 1, 'New household connection request', NULL, 'active'],
            [11, 1, 'Disconnected water supply', NULL, 'active'],
            [12, 2, 'Broken borehole', NULL, 'active'],
            [13, 2, 'Faulty hand pump', NULL, 'active'],
            [14, 2, 'Dry well', NULL, 'active'],
            [15, 2, 'Contaminated well water', NULL, 'active'],
            [16, 2, 'Community water shortage', NULL, 'active'],
            [17, 2, 'Lack of borehole maintenance', NULL, 'active'],
            [18, 2, 'Broken overhead water tank', NULL, 'active'],
            [19, 2, 'Long distance to water source', NULL, 'active'],
            [20, 2, 'Seasonal water scarcity', NULL, 'active'],
            [21, 2, 'Request for new borehole', NULL, 'active'],
            [22, 2, 'Poor water management committee', NULL, 'active'],
            [23, 3, 'Flooding due to drainage overflow', NULL, 'active'],
            [24, 3, 'Damaged culverts', NULL, 'active'],
            [25, 3, 'Poor storm water channels', NULL, 'active'],
            [26, 3, 'Blocked waterways', NULL, 'active'],
            [27, 3, 'Erosion from water runoff', NULL, 'active'],
            [28, 3, 'Collapsed embankments', NULL, 'active'],
            [29, 3, 'Poor water diversion systems', NULL, 'active'],
            [30, 3, 'Overflowing dams', NULL, 'active'],
            [31, 3, 'Water infrastructure neglect', NULL, 'active'],
            [32, 3, 'Request for flood prevention works', NULL, 'active'],
            [33, 4, 'Total power outage', NULL, 'active'],
            [34, 4, 'Frequent power cuts (dumsor)', NULL, 'active'],
            [35, 4, 'Low voltage', NULL, 'active'],
            [36, 4, 'Power fluctuations', NULL, 'active'],
            [37, 4, 'Transformer overload', NULL, 'active'],
            [38, 4, 'Burnt transformer', NULL, 'active'],
            [39, 4, 'Scheduled outage complaints', NULL, 'active'],
            [40, 4, 'Unannounced outages', NULL, 'active'],
            [41, 4, 'Community blackout', NULL, 'active'],
            [42, 4, 'Power rationing issues', NULL, 'active'],
            [43, 5, 'Fallen electric poles', NULL, 'active'],
            [44, 5, 'Exposed cables', NULL, 'active'],
            [45, 5, 'Broken cross arms', NULL, 'active'],
            [46, 5, 'Damaged transformers', NULL, 'active'],
            [47, 5, 'Leaning electric poles', NULL, 'active'],
            [48, 5, 'Street wiring hazards', NULL, 'active'],
            [49, 5, 'Old electrical installations', NULL, 'active'],
            [50, 5, 'Substation faults', NULL, 'active'],
            [51, 5, 'Illegal power connections', NULL, 'active'],
            [52, 5, 'Infrastructure vandalism', NULL, 'active'],
            [53, 6, 'Non-functional streetlights', NULL, 'active'],
            [54, 6, 'Broken streetlight poles', NULL, 'active'],
            [55, 6, 'Missing bulbs', NULL, 'active'],
            [56, 6, 'Poorly lit roads', NULL, 'active'],
            [57, 6, 'Vandalized streetlights', NULL, 'active'],
            [58, 6, 'Delayed repairs', NULL, 'active'],
            [59, 6, 'Newly installed lights not working', NULL, 'active'],
            [60, 6, 'Faulty solar streetlights', NULL, 'active'],
            [61, 6, 'Request for new streetlights', NULL, 'active'],
            [62, 6, 'Unsafe dark areas', NULL, 'active'],
            [63, 7, 'Potholes', NULL, 'active'],
            [64, 7, 'Erosion damage', NULL, 'active'],
            [65, 7, 'Muddy roads during rains', NULL, 'active'],
            [66, 7, 'Dusty roads during dry season', NULL, 'active'],
            [67, 7, 'Impassable roads', NULL, 'active'],
            [68, 7, 'Broken culverts', NULL, 'active'],
            [69, 7, 'Road narrowing', NULL, 'active'],
            [70, 7, 'Poor drainage', NULL, 'active'],
            [71, 7, 'Road shoulder collapse', NULL, 'active'],
            [72, 7, 'Delayed road maintenance', NULL, 'active'],
            [73, 8, 'Damaged asphalt roads', NULL, 'active'],
            [74, 8, 'Flooded streets', NULL, 'active'],
            [75, 8, 'Poor road markings', NULL, 'active'],
            [76, 8, 'Missing road signs', NULL, 'active'],
            [77, 8, 'Traffic congestion points', NULL, 'active'],
            [78, 8, 'Accidents due to road condition', NULL, 'active'],
            [79, 8, 'Street encroachment', NULL, 'active'],
            [80, 8, 'Broken speed ramps', NULL, 'active'],
            [81, 8, 'Uneven road surfaces', NULL, 'active'],
            [82, 8, 'Pedestrian safety issues', NULL, 'active'],
            [83, 9, 'Collapsed bridges', NULL, 'active'],
            [84, 9, 'Weak wooden bridges', NULL, 'active'],
            [85, 9, 'Damaged culverts', NULL, 'active'],
            [86, 9, 'Unsafe footbridges', NULL, 'active'],
            [87, 9, 'Flood-prone crossings', NULL, 'active'],
            [88, 9, 'Bridge erosion', NULL, 'active'],
            [89, 9, 'Missing guardrails', NULL, 'active'],
            [90, 9, 'Structural cracks', NULL, 'active'],
            [91, 9, 'Overloaded bridges', NULL, 'active'],
            [92, 9, 'Request for new bridge', NULL, 'active'],
            [93, 10, 'Refuse not collected', NULL, 'active'],
            [94, 10, 'Overflowing waste containers', NULL, 'active'],
            [95, 10, 'Illegal dumping', NULL, 'active'],
            [96, 10, 'Lack of waste bins', NULL, 'active'],
            [97, 10, 'Burning of refuse', NULL, 'active'],
            [98, 10, 'Poor landfill management', NULL, 'active'],
            [99, 10, 'Waste collection delays', NULL, 'active'],
            [100, 10, 'Community filth', NULL, 'active'],
            [101, 10, 'Market sanitation issues', NULL, 'active'],
            [102, 10, 'Request for waste skips', NULL, 'active'],
            [103, 11, 'Blocked drains', NULL, 'active'],
            [104, 11, 'Overflowing gutters', NULL, 'active'],
            [105, 11, 'Sewage leaks', NULL, 'active'],
            [106, 11, 'Open drains', NULL, 'active'],
            [107, 11, 'Flooding due to poor drainage', NULL, 'active'],
            [108, 11, 'Broken manholes', NULL, 'active'],
            [109, 11, 'Poor drain construction', NULL, 'active'],
            [110, 11, 'Stagnant water', NULL, 'active'],
            [111, 11, 'Drain siltation', NULL, 'active'],
            [112, 11, 'Drain maintenance delays', NULL, 'active'],
            [113, 12, 'Broken public toilets', NULL, 'active'],
            [114, 12, 'No toilet facilities', NULL, 'active'],
            [115, 12, 'Poorly maintained toilets', NULL, 'active'],
            [116, 12, 'Open defecation', NULL, 'active'],
            [117, 12, 'Lack of handwashing facilities', NULL, 'active'],
            [118, 12, 'Bad odor complaints', NULL, 'active'],
            [119, 12, 'Toilet user fee issues', NULL, 'active'],
            [120, 12, 'Unsafe toilet structures', NULL, 'active'],
            [121, 12, 'Toilet management problems', NULL, 'active'],
            [122, 12, 'Request for new toilet facility', NULL, 'active'],
            [123, 13, 'No health facility nearby', NULL, 'active'],
            [124, 13, 'Dilapidated clinic buildings', NULL, 'active'],
            [125, 13, 'Lack of beds', NULL, 'active'],
            [126, 13, 'Poor sanitation in facilities', NULL, 'active'],
            [127, 13, 'No electricity in clinic', NULL, 'active'],
            [128, 13, 'No water in facility', NULL, 'active'],
            [129, 13, 'Overcrowded facilities', NULL, 'active'],
            [130, 13, 'Facility expansion request', NULL, 'active'],
            [131, 13, 'Unsafe facility structures', NULL, 'active'],
            [132, 13, 'Delayed facility completion', NULL, 'active'],
            [133, 14, 'Shortage of doctors', NULL, 'active'],
            [134, 14, 'Shortage of nurses', NULL, 'active'],
            [135, 14, 'Staff absenteeism', NULL, 'active'],
            [136, 14, 'Poor staff attitude', NULL, 'active'],
            [137, 14, 'Long waiting times', NULL, 'active'],
            [138, 14, 'Emergency response delays', NULL, 'active'],
            [139, 14, 'Poor maternal care', NULL, 'active'],
            [140, 14, 'Child health services issues', NULL, 'active'],
            [141, 14, 'Inadequate night services', NULL, 'active'],
            [142, 14, 'Staff accommodation issues', NULL, 'active'],
            [143, 15, 'Lack of essential drugs', NULL, 'active'],
            [144, 15, 'Expired medicines', NULL, 'active'],
            [145, 15, 'Broken medical equipment', NULL, 'active'],
            [146, 15, 'No ambulance service', NULL, 'active'],
            [147, 15, 'Disease outbreak reports', NULL, 'active'],
            [148, 15, 'Poor vaccination coverage', NULL, 'active'],
            [149, 15, 'Malaria prevalence', NULL, 'active'],
            [150, 15, 'Cholera risk', NULL, 'active'],
            [151, 15, 'Public health education gaps', NULL, 'active'],
            [152, 15, 'Medical outreach request', NULL, 'active'],
            [153, 16, 'Dilapidated classrooms', NULL, 'active'],
            [154, 16, 'School roofs leaking', NULL, 'active'],
            [155, 16, 'Cracked walls', NULL, 'active'],
            [156, 16, 'No school buildings', NULL, 'active'],
            [157, 16, 'Overcrowded classrooms', NULL, 'active'],
            [158, 16, 'Incomplete school projects', NULL, 'active'],
            [159, 16, 'Unsafe school structures', NULL, 'active'],
            [160, 16, 'Lack of electricity', NULL, 'active'],
            [161, 16, 'Lack of water', NULL, 'active'],
            [162, 16, 'Fence/security issues', NULL, 'active'],
            [163, 17, 'Teacher shortage', NULL, 'active'],
            [164, 17, 'Teacher absenteeism', NULL, 'active'],
            [165, 17, 'Poor teaching quality', NULL, 'active'],
            [166, 17, 'Lack of textbooks', NULL, 'active'],
            [167, 17, 'No teaching aids', NULL, 'active'],
            [168, 17, 'Poor student performance', NULL, 'active'],
            [169, 17, 'Overloaded teachers', NULL, 'active'],
            [170, 17, 'Untrained teachers', NULL, 'active'],
            [171, 17, 'Poor supervision', NULL, 'active'],
            [172, 17, 'Curriculum implementation issues', NULL, 'active'],
            [173, 18, 'Lack of desks/furniture', NULL, 'active'],
            [174, 18, 'School feeding issues', NULL, 'active'],
            [175, 18, 'Long distance to school', NULL, 'active'],
            [176, 18, 'Unsafe routes to school', NULL, 'active'],
            [177, 18, 'School sanitation issues', NULL, 'active'],
            [178, 18, 'No disability access', NULL, 'active'],
            [179, 18, 'Dropout cases', NULL, 'active'],
            [180, 18, 'Child labour concerns', NULL, 'active'],
            [181, 18, 'School uniforms assistance', NULL, 'active'],
            [182, 18, 'Sanitary pad support', NULL, 'active'],
            [183, 19, 'Crop failure', NULL, 'active'],
            [184, 19, 'Pest infestation', NULL, 'active'],
            [185, 19, 'Plant disease outbreak', NULL, 'active'],
            [186, 19, 'Poor soil fertility', NULL, 'active'],
            [187, 19, 'Lack of seeds', NULL, 'active'],
            [188, 19, 'Lack of fertilizer', NULL, 'active'],
            [189, 19, 'Poor extension services', NULL, 'active'],
            [190, 19, 'Climate impact on crops', NULL, 'active'],
            [191, 19, 'Post-harvest losses', NULL, 'active'],
            [192, 19, 'Request for farm inputs', NULL, 'active'],
            [193, 20, 'Livestock disease outbreak', NULL, 'active'],
            [194, 20, 'Animal deaths', NULL, 'active'],
            [195, 20, 'Lack of veterinary services', NULL, 'active'],
            [196, 20, 'Feed shortages', NULL, 'active'],
            [197, 20, 'Poor animal housing', NULL, 'active'],
            [198, 20, 'Theft of livestock', NULL, 'active'],
            [199, 20, 'Poultry disease', NULL, 'active'],
            [200, 20, 'Fish pond collapse', NULL, 'active'],
            [201, 20, 'Lack of fingerlings', NULL, 'active'],
            [202, 20, 'Request for livestock support', NULL, 'active'],
            [203, 21, 'Poor farm roads', NULL, 'active'],
            [204, 21, 'Lack of storage facilities', NULL, 'active'],
            [205, 21, 'No drying platforms', NULL, 'active'],
            [206, 21, 'Market access problems', NULL, 'active'],
            [207, 21, 'Poor irrigation systems', NULL, 'active'],
            [208, 21, 'Broken dams', NULL, 'active'],
            [209, 21, 'Farm tool shortages', NULL, 'active'],
            [210, 21, 'Lack of processing centers', NULL, 'active'],
            [211, 21, 'Poor pricing issues', NULL, 'active'],
            [212, 21, 'Market infrastructure needs', NULL, 'active'],
            [213, 22, 'Youth unemployment', NULL, 'active'],
            [214, 22, 'Graduate unemployment', NULL, 'active'],
            [215, 22, 'Long-term unemployment', NULL, 'active'],
            [216, 22, 'Seasonal job loss', NULL, 'active'],
            [217, 22, 'School leavers unemployment', NULL, 'active'],
            [218, 22, 'Lack of local jobs', NULL, 'active'],
            [219, 22, 'Job mismatch', NULL, 'active'],
            [220, 22, 'Underemployment', NULL, 'active'],
            [221, 22, 'Community unemployment crisis', NULL, 'active'],
            [222, 22, 'Employment support request', NULL, 'active'],
            [223, 23, 'No vocational centers', NULL, 'active'],
            [224, 23, 'Lack of apprenticeship opportunities', NULL, 'active'],
            [225, 23, 'Skills training request', NULL, 'active'],
            [226, 23, 'Poor training facilities', NULL, 'active'],
            [227, 23, 'Inaccessible training programs', NULL, 'active'],
            [228, 23, 'Cost of training', NULL, 'active'],
            [229, 23, 'Inadequate instructors', NULL, 'active'],
            [230, 23, 'Certification delays', NULL, 'active'],
            [231, 23, 'Outdated training programs', NULL, 'active'],
            [232, 23, 'Youth skills development request', NULL, 'active'],
            [233, 24, 'Unpaid wages', NULL, 'active'],
            [234, 24, 'Delayed salaries', NULL, 'active'],
            [235, 24, 'Unsafe working conditions', NULL, 'active'],
            [236, 24, 'Workplace harassment', NULL, 'active'],
            [237, 24, 'Employment discrimination', NULL, 'active'],
            [238, 24, 'Contract violations', NULL, 'active'],
            [239, 24, 'Child labour', NULL, 'active'],
            [240, 24, 'Employer misconduct', NULL, 'active'],
            [241, 24, 'Casual labour exploitation', NULL, 'active'],
            [242, 24, 'Labour dispute resolution request', NULL, 'active'],
            [243, 25, 'Extreme poverty assistance', NULL, 'active'],
            [244, 25, 'Emergency financial support', NULL, 'active'],
            [245, 25, 'Food aid request', NULL, 'active'],
            [246, 25, 'Rent assistance', NULL, 'active'],
            [247, 25, 'School fees support', NULL, 'active'],
            [248, 25, 'Medical bill assistance', NULL, 'active'],
            [249, 25, 'Funeral support', NULL, 'active'],
            [250, 25, 'Disaster relief support', NULL, 'active'],
            [251, 25, 'Clothing assistance', NULL, 'active'],
            [252, 25, 'Household support request', NULL, 'active'],
            [253, 26, 'Persons with disabilities support', NULL, 'active'],
            [254, 26, 'Elderly care support', NULL, 'active'],
            [255, 26, 'Orphans support', NULL, 'active'],
            [256, 26, 'Widows support', NULL, 'active'],
            [257, 26, 'Single parent assistance', NULL, 'active'],
            [258, 26, 'Street children support', NULL, 'active'],
            [259, 26, 'Abandoned persons', NULL, 'active'],
            [260, 26, 'Mental health support', NULL, 'active'],
            [261, 26, 'Chronic illness support', NULL, 'active'],
            [262, 26, 'Caregiver assistance', NULL, 'active'],
            [263, 27, 'LEAP enrollment issues', NULL, 'active'],
            [264, 27, 'NHIS registration problems', NULL, 'active'],
            [265, 27, 'Disability fund access', NULL, 'active'],
            [266, 27, 'Social grants delays', NULL, 'active'],
            [267, 27, 'Beneficiary exclusion complaints', NULL, 'active'],
            [268, 27, 'Payment irregularities', NULL, 'active'],
            [269, 27, 'Program awareness gaps', NULL, 'active'],
            [270, 27, 'Complaints about officials', NULL, 'active'],
            [271, 27, 'Verification delays', NULL, 'active'],
            [272, 27, 'Program expansion request', NULL, 'active'],
            [273, 28, 'Theft incidents', NULL, 'active'],
            [274, 28, 'Armed robbery concerns', NULL, 'active'],
            [275, 28, 'Community insecurity', NULL, 'active'],
            [276, 28, 'Police response delays', NULL, 'active'],
            [277, 28, 'Vigilante activity', NULL, 'active'],
            [278, 28, 'Drug abuse concerns', NULL, 'active'],
            [279, 28, 'Domestic violence', NULL, 'active'],
            [280, 28, 'Night security issues', NULL, 'active'],
            [281, 28, 'Unsafe public spaces', NULL, 'active'],
            [282, 28, 'Community patrol request', NULL, 'active'],
            [283, 29, 'Land disputes', NULL, 'active'],
            [284, 29, 'Boundary conflicts', NULL, 'active'],
            [285, 29, 'Illegal land sales', NULL, 'active'],
            [286, 29, 'Housing demolition threats', NULL, 'active'],
            [287, 29, 'Poor housing conditions', NULL, 'active'],
            [288, 29, 'Encroachment issues', NULL, 'active'],
            [289, 29, 'Building permit problems', NULL, 'active'],
            [290, 29, 'Housing assistance request', NULL, 'active'],
            [291, 29, 'Settlement planning issues', NULL, 'active'],
            [292, 29, 'Land documentation issues', NULL, 'active'],
            [293, 30, 'Abuse of authority', NULL, 'active'],
            [294, 30, 'Corruption allegations', NULL, 'active'],
            [295, 30, 'Poor service delivery', NULL, 'active'],
            [296, 30, 'Community leadership disputes', NULL, 'active'],
            [297, 30, 'Exclusion from government programs', NULL, 'active'],
            [298, 30, 'Electoral concerns', NULL, 'active'],
            [299, 30, 'Public engagement complaints', NULL, 'active'],
            [300, 30, 'Lack of information', NULL, 'active'],
            [301, 30, 'Petition follow-up issues', NULL, 'active'],
            [302, 30, 'General civic complaint', NULL, 'active'],
        ];

        foreach ($subSectors as $sub) {
            $this->execute(sprintf(
                "INSERT INTO sub_sectors (id, sector_id, name, description, status, created_at, updated_at) 
                 VALUES (%d, %d, '%s', %s, '%s', NOW(), NOW()) 
                 ON DUPLICATE KEY UPDATE sector_id=%d, name='%s', description=%s, status='%s', updated_at=NOW()",
                $sub[0], $sub[1], addslashes($sub[2]), ($sub[3] === NULL ? 'NULL' : "'".addslashes($sub[3])."'"), $sub[4],
                $sub[1], addslashes($sub[2]), ($sub[3] === NULL ? 'NULL' : "'".addslashes($sub[3])."'"), $sub[4]
            ));
        }

        $this->execute("SET FOREIGN_KEY_CHECKS = 1");

        echo "✅ Seeding completed successfully for Locations, Categories, Sectors, and Sub-Sectors!\n";
    }
}
