<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

class LocationSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     */
    public function run(): void
    {
        $data = [
            ['id' => 1, 'name' => 'BEDII', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 2, 'name' => 'ABOANIDUA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 3, 'name' => 'NTRENTRESO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 4, 'name' => 'AKOTI', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 5, 'name' => 'PABOASE', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 6, 'name' => 'APPIAHKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 7, 'name' => 'AHWIAA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 8, 'name' => 'FUTA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 9, 'name' => 'PENAKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 10, 'name' => 'NYAMEBEKYERE', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 11, 'name' => 'BOSOMOISO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 12, 'name' => 'AFEREE', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 13, 'name' => 'ABODUAM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 14, 'name' => 'EWIASE-NGAKAIN', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 15, 'name' => 'AMAFIE', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 16, 'name' => 'ABOBOYAA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 17, 'name' => 'WIAWSO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 18, 'name' => 'KESSEKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 19, 'name' => 'AHWIAM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 20, 'name' => 'MPOMAM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 21, 'name' => 'DWENASE', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 22, 'name' => 'NSUONSUA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 23, 'name' => 'TANOSO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 24, 'name' => 'DATANO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 25, 'name' => 'AHOKWAA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 26, 'name' => 'DOMEABRA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 27, 'name' => 'KETEBOI', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 28, 'name' => 'PUNIKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 29, 'name' => 'CAMP', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 30, 'name' => 'ANYINABIRIM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 31, 'name' => 'ABRABRA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 32, 'name' => 'NKONYA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 33, 'name' => 'ATTORKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 34, 'name' => 'SUI', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 35, 'name' => 'BOAKO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 36, 'name' => 'AKURAFU', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 37, 'name' => 'GYAMPOKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 38, 'name' => 'AMPABAME', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 39, 'name' => 'ABOAGYEKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 40, 'name' => 'BBB', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 41, 'name' => 'KUNUMA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 42, 'name' => 'AFRIMKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 43, 'name' => 'AKYEAKYEN', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 44, 'name' => 'KANKYEABO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 45, 'name' => 'A', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 46, 'name' => 'ASAFO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 47, 'name' => 'ASAWINSO', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 48, 'name' => 'KOJINA', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 49, 'name' => 'ESSAKROM', 'type' => 'community', 'parent_id' => null, 'status' => 'active'],
            ['id' => 50, 'name' => 'AGONA SAFO', 'type' => 'suburb', 'parent_id' => 1, 'status' => 'active'],
            ['id' => 51, 'name' => 'OLD BEDII', 'type' => 'suburb', 'parent_id' => 1, 'status' => 'active'],
            ['id' => 52, 'name' => 'LARWEHKROM', 'type' => 'community', 'parent_id' => 5, 'status' => 'active'],
            ['id' => 53, 'name' => 'PROJECT', 'type' => 'suburb', 'parent_id' => 52, 'status' => 'active'],
            ['id' => 54, 'name' => 'KWAME ANINIKROM', 'type' => 'suburb', 'parent_id' => 52, 'status' => 'active'],
            ['id' => 55, 'name' => 'KYEREBOSO', 'type' => 'suburb', 'parent_id' => 7, 'status' => 'active'],
            ['id' => 56, 'name' => 'ALOMUM', 'type' => 'community', 'parent_id' => 10, 'status' => 'active'],
            ['id' => 57, 'name' => 'DWENEWOHO', 'type' => 'community', 'parent_id' => 12, 'status' => 'active'],
            ['id' => 58, 'name' => 'BETEKYE', 'type' => 'suburb', 'parent_id' => 13, 'status' => 'active'],
            ['id' => 59, 'name' => 'GARDEN', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 60, 'name' => 'OLD ADIEMBRA', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 61, 'name' => 'NEW ADIEMBRA', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 62, 'name' => 'SUSUMINITE3', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 63, 'name' => 'NEWTOWN', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 64, 'name' => 'SOMAAKROM', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 65, 'name' => 'ABUOTEM', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 66, 'name' => 'KWASIPATABO', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 67, 'name' => 'ASAMAN', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 68, 'name' => 'SOUTH AFRICA', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 69, 'name' => 'AKAALOMBO', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 70, 'name' => 'ASIKAFUO AMMANTEM', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 71, 'name' => 'MEMPE-ASEM', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 72, 'name' => 'ZONGO', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 73, 'name' => 'LOWCOST', 'type' => 'suburb', 'parent_id' => 17, 'status' => 'active'],
            ['id' => 74, 'name' => 'KWAADUKROM', 'type' => 'suburb', 'parent_id' => 19, 'status' => 'active'],
            ['id' => 75, 'name' => 'NO.2 (BOAMAKROM)', 'type' => 'suburb', 'parent_id' => 19, 'status' => 'active'],
            ['id' => 76, 'name' => 'GYATOKROM', 'type' => 'community', 'parent_id' => 19, 'status' => 'active'],
            ['id' => 77, 'name' => 'ATEKYEM', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 78, 'name' => 'AKURASE', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 79, 'name' => 'EIGHTEEN', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 80, 'name' => 'ZONGO', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 81, 'name' => 'NEW SITE', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 82, 'name' => 'COMPOUND', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 83, 'name' => 'KOKOKRO', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 84, 'name' => 'NSUEKRO', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 85, 'name' => 'KUZENSO', 'type' => 'suburb', 'parent_id' => 21, 'status' => 'active'],
            ['id' => 86, 'name' => 'ANGLO', 'type' => 'community', 'parent_id' => 22, 'status' => 'active'],
            ['id' => 87, 'name' => 'BAAKONGA', 'type' => 'community', 'parent_id' => 22, 'status' => 'active'],
            ['id' => 88, 'name' => 'ENSONYAMEYE', 'type' => 'community', 'parent_id' => 22, 'status' => 'active'],
            ['id' => 89, 'name' => 'KWAMEBUO', 'type' => 'community', 'parent_id' => 22, 'status' => 'active'],
            ['id' => 90, 'name' => 'KROBOM', 'type' => 'community', 'parent_id' => 22, 'status' => 'active'],
            ['id' => 91, 'name' => 'AYILEKRO', 'type' => 'community', 'parent_id' => 22, 'status' => 'active'],
            ['id' => 92, 'name' => 'KWASI ARMAKROM', 'type' => 'suburb', 'parent_id' => 89, 'status' => 'active'],
            ['id' => 93, 'name' => 'ADAMU', 'type' => 'suburb', 'parent_id' => 91, 'status' => 'active'],
            ['id' => 94, 'name' => 'ABOPROE', 'type' => 'suburb', 'parent_id' => 91, 'status' => 'active'],
            ['id' => 95, 'name' => 'AHODWO', 'type' => 'suburb', 'parent_id' => 23, 'status' => 'active'],
            ['id' => 96, 'name' => 'DIVISION', 'type' => 'suburb', 'parent_id' => 23, 'status' => 'active'],
            ['id' => 97, 'name' => 'EFO JUNCTION', 'type' => 'suburb', 'parent_id' => 23, 'status' => 'active'],
            ['id' => 98, 'name' => 'FUAKYEKROM', 'type' => 'community', 'parent_id' => 23, 'status' => 'active'],
            ['id' => 99, 'name' => 'NYAMEGYESO', 'type' => 'community', 'parent_id' => 23, 'status' => 'active'],
            ['id' => 100, 'name' => 'ESONEBIAGYA', 'type' => 'suburb', 'parent_id' => 98, 'status' => 'active'],
            ['id' => 101, 'name' => 'MEMPE-ASEM', 'type' => 'suburb', 'parent_id' => 98, 'status' => 'active'],
            ['id' => 102, 'name' => 'KWADWO ANTO', 'type' => 'suburb', 'parent_id' => 98, 'status' => 'active'],
            ['id' => 103, 'name' => 'KUSASI-LINE', 'type' => 'suburb', 'parent_id' => 24, 'status' => 'active'],
            ['id' => 104, 'name' => 'SUHENSO', 'type' => 'community', 'parent_id' => 25, 'status' => 'active'],
            ['id' => 105, 'name' => 'OWUO ABOROSO', 'type' => 'suburb', 'parent_id' => 26, 'status' => 'active'],
            ['id' => 106, 'name' => 'BOWOBRA', 'type' => 'community', 'parent_id' => 26, 'status' => 'active'],
            ['id' => 107, 'name' => 'KYEAMEKRO', 'type' => 'community', 'parent_id' => 26, 'status' => 'active'],
            ['id' => 108, 'name' => 'APENTEMADI', 'type' => 'community', 'parent_id' => 26, 'status' => 'active'],
            ['id' => 109, 'name' => 'NYAME NNAE', 'type' => 'community', 'parent_id' => 26, 'status' => 'active'],
            ['id' => 110, 'name' => 'SWANZY', 'type' => 'community', 'parent_id' => 26, 'status' => 'active'],
            ['id' => 111, 'name' => 'PIASE', 'type' => 'community', 'parent_id' => 26, 'status' => 'active'],
            ['id' => 112, 'name' => 'OBIA NTOBI', 'type' => 'suburb', 'parent_id' => 109, 'status' => 'active'],
            ['id' => 113, 'name' => 'OSEI MPAMBRO', 'type' => 'suburb', 'parent_id' => 109, 'status' => 'active'],
            ['id' => 114, 'name' => 'KRAMO TENTEN', 'type' => 'suburb', 'parent_id' => 109, 'status' => 'active'],
            ['id' => 115, 'name' => 'NYAME NNAI ZONGO', 'type' => 'suburb', 'parent_id' => 109, 'status' => 'active'],
            ['id' => 116, 'name' => 'MORGAN', 'type' => 'suburb', 'parent_id' => 110, 'status' => 'active'],
            ['id' => 117, 'name' => 'ADIYAAKRO', 'type' => 'suburb', 'parent_id' => 110, 'status' => 'active'],
            ['id' => 118, 'name' => 'SHED', 'type' => 'suburb', 'parent_id' => 110, 'status' => 'active'],
            ['id' => 119, 'name' => 'AMADU KROM', 'type' => 'suburb', 'parent_id' => 110, 'status' => 'active'],
            ['id' => 120, 'name' => 'TUPA', 'type' => 'suburb', 'parent_id' => 110, 'status' => 'active'],
            ['id' => 121, 'name' => 'MATAPOLI', 'type' => 'suburb', 'parent_id' => 111, 'status' => 'active'],
            ['id' => 122, 'name' => 'EMIESO', 'type' => 'suburb', 'parent_id' => 27, 'status' => 'active'],
            ['id' => 123, 'name' => 'GYAASEHENE', 'type' => 'suburb', 'parent_id' => 27, 'status' => 'active'],
            ['id' => 124, 'name' => 'KAINA-C', 'type' => 'suburb', 'parent_id' => 27, 'status' => 'active'],
            ['id' => 125, 'name' => 'GARIBAKRO', 'type' => 'suburb', 'parent_id' => 27, 'status' => 'active'],
            ['id' => 126, 'name' => 'ADOWA NKWANTA', 'type' => 'suburb', 'parent_id' => 28, 'status' => 'active'],
            ['id' => 127, 'name' => 'ADUHENEKROM', 'type' => 'suburb', 'parent_id' => 28, 'status' => 'active'],
            ['id' => 128, 'name' => 'ADENKYIN', 'type' => 'suburb', 'parent_id' => 28, 'status' => 'active'],
            ['id' => 129, 'name' => 'KRAMOKRO', 'type' => 'community', 'parent_id' => 28, 'status' => 'active'],
            ['id' => 130, 'name' => 'AGYA AKUFO', 'type' => 'suburb', 'parent_id' => 129, 'status' => 'active'],
            ['id' => 131, 'name' => 'KOFIKROM', 'type' => 'suburb', 'parent_id' => 29, 'status' => 'active'],
            ['id' => 132, 'name' => 'BOMODEN', 'type' => 'suburb', 'parent_id' => 29, 'status' => 'active'],
            ['id' => 133, 'name' => 'BREDI', 'type' => 'suburb', 'parent_id' => 29, 'status' => 'active'],
            ['id' => 134, 'name' => 'ASANTEKROM', 'type' => 'suburb', 'parent_id' => 29, 'status' => 'active'],
            ['id' => 135, 'name' => 'POWERKROM', 'type' => 'suburb', 'parent_id' => 29, 'status' => 'active'],
            ['id' => 136, 'name' => 'AKUAPIM NKWANTA', 'type' => 'suburb', 'parent_id' => 29, 'status' => 'active'],
            ['id' => 137, 'name' => 'BANGROMESAA', 'type' => 'suburb', 'parent_id' => 29, 'status' => 'active'],
            ['id' => 138, 'name' => 'GYIDI', 'type' => 'suburb', 'parent_id' => 30, 'status' => 'active'],
            ['id' => 139, 'name' => 'KOFORIDUA', 'type' => 'suburb', 'parent_id' => 30, 'status' => 'active'],
            ['id' => 140, 'name' => 'MILE 2', 'type' => 'community', 'parent_id' => 30, 'status' => 'active'],
            ['id' => 141, 'name' => 'MILE-3', 'type' => 'community', 'parent_id' => 30, 'status' => 'active'],
            ['id' => 142, 'name' => 'MILE-4', 'type' => 'community', 'parent_id' => 30, 'status' => 'active'],
            ['id' => 143, 'name' => 'MILE-5', 'type' => 'community', 'parent_id' => 30, 'status' => 'active'],
            ['id' => 144, 'name' => 'MILE-3 FOREST', 'type' => 'suburb', 'parent_id' => 141, 'status' => 'active'],
            ['id' => 145, 'name' => 'GYAAKYE', 'type' => 'suburb', 'parent_id' => 141, 'status' => 'active'],
            ['id' => 146, 'name' => 'MILE-4 FOREST', 'type' => 'suburb', 'parent_id' => 142, 'status' => 'active'],
            ['id' => 147, 'name' => 'ASUOGYA', 'type' => 'suburb', 'parent_id' => 143, 'status' => 'active'],
            ['id' => 148, 'name' => 'KOO NSIA', 'type' => 'suburb', 'parent_id' => 143, 'status' => 'active'],
            ['id' => 149, 'name' => 'NYAME NNAE-ABRABRA', 'type' => 'suburb', 'parent_id' => 31, 'status' => 'active'],
            ['id' => 150, 'name' => 'ABRABRA FOREST', 'type' => 'suburb', 'parent_id' => 31, 'status' => 'active'],
            ['id' => 151, 'name' => 'KUMIKROM', 'type' => 'suburb', 'parent_id' => 31, 'status' => 'active'],
            ['id' => 152, 'name' => 'PEWODIE', 'type' => 'community', 'parent_id' => 32, 'status' => 'active'],
            ['id' => 153, 'name' => 'SUI NKWANTA', 'type' => 'community', 'parent_id' => 32, 'status' => 'active'],
            ['id' => 154, 'name' => 'ATTA CAMP', 'type' => 'community', 'parent_id' => 32, 'status' => 'active'],
            ['id' => 155, 'name' => 'PAPA KWAME', 'type' => 'suburb', 'parent_id' => 152, 'status' => 'active'],
            ['id' => 156, 'name' => 'MFUMKROM', 'type' => 'suburb', 'parent_id' => 154, 'status' => 'active'],
            ['id' => 157, 'name' => 'KROBO LINE', 'type' => 'suburb', 'parent_id' => 154, 'status' => 'active'],
            ['id' => 158, 'name' => 'BARRACKS', 'type' => 'suburb', 'parent_id' => 35, 'status' => 'active'],
            ['id' => 159, 'name' => 'BUADAC', 'type' => 'suburb', 'parent_id' => 35, 'status' => 'active'],
            ['id' => 160, 'name' => 'ASUOEBA', 'type' => 'suburb', 'parent_id' => 158, 'status' => 'active'],
            ['id' => 161, 'name' => 'KWANANE', 'type' => 'community', 'parent_id' => 35, 'status' => 'active'],
            ['id' => 162, 'name' => 'ABODUAM', 'type' => 'suburb', 'parent_id' => 161, 'status' => 'active'],
            ['id' => 163, 'name' => 'TEABANTE', 'type' => 'suburb', 'parent_id' => 161, 'status' => 'active'],
            ['id' => 164, 'name' => 'GRUMAHENE', 'type' => 'suburb', 'parent_id' => 161, 'status' => 'active'],
            ['id' => 165, 'name' => 'KWADWO HUNU', 'type' => 'suburb', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 166, 'name' => 'SHED', 'type' => 'suburb', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 167, 'name' => 'KUMORKRO', 'type' => 'suburb', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 168, 'name' => 'AMPROMBI', 'type' => 'suburb', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 169, 'name' => 'BOADUKROM', 'type' => 'suburb', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 170, 'name' => 'YAWKWATIAKRO', 'type' => 'suburb', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 171, 'name' => 'FAWOMAN', 'type' => 'community', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 172, 'name' => 'NYETINA', 'type' => 'community', 'parent_id' => 36, 'status' => 'active'],
            ['id' => 173, 'name' => 'ABONSE', 'type' => 'community', 'parent_id' => 37, 'status' => 'active'],
            ['id' => 174, 'name' => 'BEKYIWA', 'type' => 'community', 'parent_id' => 37, 'status' => 'active'],
            ['id' => 175, 'name' => 'AWUTU', 'type' => 'suburb', 'parent_id' => 173, 'status' => 'active'],
            ['id' => 176, 'name' => 'POSTMASTER', 'type' => 'suburb', 'parent_id' => 174, 'status' => 'active'],
            ['id' => 177, 'name' => 'MANGOASE', 'type' => 'suburb', 'parent_id' => 174, 'status' => 'active'],
            ['id' => 178, 'name' => 'AMANO', 'type' => 'suburb', 'parent_id' => 174, 'status' => 'active'],
            ['id' => 179, 'name' => 'OYOKO', 'type' => 'suburb', 'parent_id' => 174, 'status' => 'active'],
            ['id' => 180, 'name' => 'ABOSO', 'type' => 'suburb', 'parent_id' => 174, 'status' => 'active'],
            ['id' => 181, 'name' => 'ABIGYAN LINE', 'type' => 'suburb', 'parent_id' => 174, 'status' => 'active'],
            ['id' => 182, 'name' => 'AFADIKROM', 'type' => 'community', 'parent_id' => 38, 'status' => 'active'],
            ['id' => 183, 'name' => 'LARBIKROM', 'type' => 'community', 'parent_id' => 38, 'status' => 'active'],
            ['id' => 184, 'name' => 'MADINA', 'type' => 'community', 'parent_id' => 38, 'status' => 'active'],
            ['id' => 185, 'name' => 'KWASI ADJEIKROM', 'type' => 'suburb', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 186, 'name' => 'GYAMPO', 'type' => 'suburb', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 187, 'name' => 'DAWOME', 'type' => 'suburb', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 188, 'name' => 'OJOBI', 'type' => 'suburb', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 189, 'name' => 'ASIEDUKRO', 'type' => 'suburb', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 190, 'name' => 'AMANKWAKRO', 'type' => 'suburb', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 191, 'name' => 'BREKULINE', 'type' => 'community', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 192, 'name' => 'MENSAHLINE KWASIKRU', 'type' => 'community', 'parent_id' => 39, 'status' => 'active'],
            ['id' => 193, 'name' => 'KAE AWURADE', 'type' => 'suburb', 'parent_id' => 192, 'status' => 'active'],
            ['id' => 194, 'name' => 'TUTUCAMP', 'type' => 'suburb', 'parent_id' => 192, 'status' => 'active'],
            ['id' => 195, 'name' => 'NANA YARO', 'type' => 'suburb', 'parent_id' => 41, 'status' => 'active'],
            ['id' => 196, 'name' => 'NANA HARUNA', 'type' => 'suburb', 'parent_id' => 41, 'status' => 'active'],
            ['id' => 197, 'name' => 'SUI ANO', 'type' => 'community', 'parent_id' => 41, 'status' => 'active'],
            ['id' => 198, 'name' => 'BRE NYE KWA', 'type' => 'suburb', 'parent_id' => 44, 'status' => 'active'],
            ['id' => 199, 'name' => 'ADUANE KYEN SIKA', 'type' => 'suburb', 'parent_id' => 44, 'status' => 'active'],
            ['id' => 200, 'name' => 'ROME', 'type' => 'community', 'parent_id' => 45, 'status' => 'active'],
            ['id' => 201, 'name' => 'ANKAASE', 'type' => 'suburb', 'parent_id' => 46, 'status' => 'active'],
            ['id' => 202, 'name' => 'KWAME DRUG STORE', 'type' => 'suburb', 'parent_id' => 46, 'status' => 'active'],
            ['id' => 203, 'name' => 'ZUGU LINE', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 204, 'name' => 'GYATOKROM', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 205, 'name' => 'ACKAAKROM', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 206, 'name' => 'DE-BEAT', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 207, 'name' => 'SEFWI LINE', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 208, 'name' => 'BILI BOY', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 209, 'name' => 'OBAATAASO', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 210, 'name' => 'ZAB ZERO', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 211, 'name' => 'MARKET AREA', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 212, 'name' => 'MEMENEDA KOKOO', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 213, 'name' => 'WANOPE ASEM', 'type' => 'suburb', 'parent_id' => 47, 'status' => 'active'],
            ['id' => 214, 'name' => 'ATHURKROM', 'type' => 'suburb', 'parent_id' => 48, 'status' => 'active'],
            ['id' => 215, 'name' => 'AKWASI ADDAEKROM', 'type' => 'community', 'parent_id' => 49, 'status' => 'active'],
        ];

        $table = $this->table('locations');
        
        // Use truncate if you want to start fresh, but be careful with foreign keys
        // $table->truncate();
        
        $table->insert($data)
              ->saveData();
    }
}
